### ISSUE TITLE
[Android] Coroutine / Dispatcher.Main issue

### ISSUE THREAD

**Issue by stanrisever** [florent37/Flutter-AssetsAudioPlayer#147]
Flutter 1.17.2

My version : 

assets_audio_player: ^1.6.4+3

My version : 

**Platform (Android ) + version**

Platform : 

**Describe the bug**

 _assetsAudioPlayer.open(Playlist(
        audios: this.audios, startIndex: widget.gelenIndex),
        autoStart: false,
      **showNotification: true,  
      playInBackground: PlayInBackground.enabled**
    );
=>adding these two lines, the application closes when it comes to this page. I couldn't get rid of the error when I deleted

```dart
import 'dart:async';
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:firebase_admob/firebase_admob.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:palette_generator/palette_generator.dart';
import 'package:sound_player_ui/playListScreen.dart';
import 'package:sound_player_ui/utils/strings.dart';

import 'admob_islmeleri.dart';
import 'models/sarkilar.dart';

class MyAppp extends StatefulWidget {
  int gelenIndex;

  MyAppp(this.gelenIndex);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyAppp> {
  BannerAd myBannerAd;
  InterstitialAd myInterstitialAd;
  Color baskinRenk = Colors.pink;
  Color pasifRenk = Colors.pink[50];
  PaletteGenerator paletteGenerator;
  Sarkilar secilenSarki;
  final fontFamily = "Roboto";
  String ad = "";
  bool shuffleList = false;
  bool loopSong = false;


  final audios = <Audio>[
    /*Audio("assets/audio/adele1.mp3"),
    Audio("assets/audio/adele2.mp3"),*/
  ];

  Duration _duration = new Duration();
  Duration _position = new Duration();

  final AssetsAudioPlayer _assetsAudioPlayer = AssetsAudioPlayer();
  final List<StreamSubscription> _subscriptions = [];
  @override
  void initState() {
    super.initState();
    AdmobIslemleri.admobInitialsize();
    myBannerAd = AdmobIslemleri.BuildBannerAd();
    myBannerAd.load();

    sarkiAktar();
    secilenSarki = PlayListScreen.tumSarkilar[widget.gelenIndex];
    _assetsAudioPlayer.open(Playlist(
        audios: this.audios, startIndex: widget.gelenIndex),
        autoStart: false,
      showNotification: false,
      playInBackground: PlayInBackground.enabled
    );


    _subscriptions.add(_assetsAudioPlayer.playlistFinished.listen((data) {
      print("finished : $data   Şarkı Bittiiii");
      print("Şarkı Bittiğinde Data:$data , \ngelenŞerkıIndexNumarası:" +
          widget.gelenIndex.toString() +
          "\nŞarkı Tekrar:$loopSong \nKarışık Çal:$shuffleList \nListe Uzunluğu" +
          audios.length.toString());
         Degistir();

    })); //Şarkı Bitince Tetikleniyor.


    _subscriptions.add(_assetsAudioPlayer.playlistAudioFinished.listen((data) {
      print("playlistAudioFinished : $data");

    })); //Liste Bitince Tektikleniyor

    _subscriptions.add(_assetsAudioPlayer.current.listen((data) {
      print("current : $data");
    }));

    _subscriptions.add(_assetsAudioPlayer.isLooping
        .listen((onData) {

    })); // Loop AÇ/Kapa da Tetikleniyor.

    _subscriptions.add(_assetsAudioPlayer.isShuffling.listen((event) {
      debugPrint("Karışık Çal Liste : " + event.toString());
    }));

    baskinRengiBul();
  }

  @override
  void dispose() {
    _assetsAudioPlayer.dispose();
    if (myBannerAd != null) {
      myBannerAd.dispose();
    }

    if (myInterstitialAd != null) {
      myInterstitialAd.dispose();
    }
    super.dispose();
  }

  void sarkiAktar() {
    for (int i = 0; i < PlayListScreen.tumSarkilar.length; i++) {
      audios.add(Audio("assets/audio/" + Strings.SARKI_LISTESI[i] + ".mp3", metas:Metas(title: Strings.SARKI_ADLARI[i],artist:"Neşeli Çocuk Şarkıları", image: MetasImage.asset("assets/images/"+Strings.RESIM_ADLARI[i]+"_buyuk.png"))));

      debugPrint("assets/audio/" + Strings.SARKI_LISTESI[i] + ".mp3");
    }
  }

  void reklamGoster() {
    myBannerAd.show();
  }

  void Degistir() {
    debugPrint("Değiştir Çalıştı");
    baskinRengiBul();
  }


  Widget adiDegistir() {
    return _assetsAudioPlayer.builderCurrent(
        builder: (BuildContext context, Playing playing){
          if(playing!=null){
            final myAudio = find(this.audios, playing.audio.assetAudioPath);
            widget.gelenIndex = int.parse(myAudio.metas.title.substring(0,2));
            debugPrint("Şarkı Numarasısıııısısısısısı :"+ widget.gelenIndex.toString());
            return Text(
              myAudio.metas.title,
              style: TextStyle(
                  color: Colors.grey[900],
                  fontFamily: fontFamily,
                  fontWeight: FontWeight.w700,
                  letterSpacing: 1.5,
                  fontSize: 20),
            );

          }
          //baskinRengiBul();
          return SizedBox();
        });
  }

  Widget resimDegistir() {
    return _assetsAudioPlayer.builderCurrent(
        builder: (BuildContext context, Playing playing){
      if(playing!=null){
        final myAudio = find(this.audios, playing.audio.assetAudioPath);
        return Image.asset(
          myAudio.metas.image.path,
          fit: BoxFit.cover,
        );
      }
       return SizedBox();
    });

  }

  void baskinRengiBul() {
    debugPrint("BaskinRengiBul Çalıştı");

    Future<PaletteGenerator> fPaletGenerator =
    PaletteGenerator.fromImageProvider(
        AssetImage("assets/images/"+Strings.RESIM_ADLARI[widget.gelenIndex]+"_buyuk.png"));

    fPaletGenerator.then((value) {
      paletteGenerator = value;
      debugPrint("secilen renk :" + paletteGenerator.dominantColor.color.toString());
      setState(() {
        baskinRenk = paletteGenerator.vibrantColor.color;
        pasifRenk = paletteGenerator.lightVibrantColor.color;
      });
    });
  }

  Widget slider(double gelenDeger, double totalDeger) {
    if (gelenDeger > totalDeger) {
      gelenDeger = totalDeger;
    }
    return Slider(
      value: gelenDeger,
      min: 0.0,
      max: totalDeger,
      divisions: 100,
      label: '${durationToString(_position)}',
      activeColor: pasifRenk,
      inactiveColor: Colors.white24,
      onChanged: (double value) {
        setState(() {
          value = value;
          seekToSecond(value.toInt());
        });
      },
      semanticFormatterCallback: (double value) {
        value = value;
        return '${value.round()}';
      },
    );
  }

  void seekToSecond(int second) {
    Duration newDuration = Duration(seconds: second);
    _assetsAudioPlayer.seek(newDuration);
  }
  Audio find(List<Audio> source, String fromPath) {
    return source.firstWhere((element) => element.path == fromPath);
  }

  @override
  Widget build(BuildContext context) {
    //reklamGoster();
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.only(bottom: 0.0, top: 25),
          child: Column(
            mainAxisSize: MainAxisSize.max,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              /*RaisedButton(
                onPressed: () {
                  _assetsAudioPlayer.open(Playlist(audios: this.audios));
                },
                child: Text("Playlist test"),
              ),*/ // Listeyi Yenile Tuşu
              /*
          RaisedButton(
                onPressed: () {
                  AssetsAudioPlayer.newPlayer()
                      .open(Audio("assets/audio/adele4.mp3"));
                },
                child: Text("Üst üste parça çalma kodu"),
              ),*/ // Üst üste parça çalma kodu
              /*Expanded(

                child: StreamBuilder(
                    stream: _assetsAudioPlayer.current,
                    builder: (BuildContext context,
                        AsyncSnapshot<Playing> snapshot) {
                      final Playing playing = snapshot.data;
                      return ListView.builder(
                        itemBuilder: (context, position) {
                          return ListTile(
                              title: Text(audios[position].path.split("/").last,
                                  style: TextStyle(
                                    color: audios[position].path == playing?.audio?.assetAudioPath
                                        ? Colors.blue
                                        : Colors.black,
                                  )),
                              onTap: () {
                                _assetsAudioPlayer.open(audios[position]);
                              });
                        },
                        itemCount: audios.length,
                      );
                    }),
              ),*/ // Şarkı Listesi
              Container(
                margin:
                EdgeInsets.only(left: 25, right: 25, bottom: 32, top: 32),
                width: double.infinity,
                height: 250,
                decoration: BoxDecoration(
                  boxShadow: [
                    new BoxShadow(
                        color: Colors.black.withOpacity(0.3),
                        offset: new Offset(0, 0),
                        blurRadius: 7.0,
                        spreadRadius: 2.5)
                  ],
                  borderRadius: new BorderRadius.all(Radius.circular(80.0)),
                ),
                child: ClipRRect(
                  child: resimDegistir(),
                  borderRadius: BorderRadius.all(Radius.circular(80)),
                ),
              ),
              Expanded(
                child: Container(
                  width: double.infinity,
                  padding: EdgeInsets.only(left: 32, right: 32),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: <Widget>[
                      Text(
                        "Neşeli Çocuk Şarkıları",
                        style: TextStyle(
                            color: Colors.grey,
                            fontFamily: fontFamily,
                            fontWeight: FontWeight.w900,
                            letterSpacing: 0.5),
                      ),
                      SizedBox(
                        width: 4,
                      ),
                      adiDegistir(),
                    ],
                  ),
                ),
              ),

              Stack(
                children: <Widget>[
                  Positioned(
                    child: Align(
                      alignment: Alignment.bottomCenter,
                      child: Container(
                        width: double.infinity,
                        height: 180,
                        decoration: BoxDecoration(
                          color: baskinRenk,
                          borderRadius: BorderRadius.only(
                            topRight: Radius.circular(80.0),
                            topLeft: Radius.circular(80.0),
                          ),
                          boxShadow: [
                            BoxShadow(
                                color: Colors.black.withOpacity(.4),
                                offset: Offset(0, 0),
                                blurRadius: 7,
                                spreadRadius: 2.5),
                          ],
                        ),
                        child: Stack(
                          children: <Widget>[
                            Column(
                              mainAxisSize: MainAxisSize.max,
                              children: <Widget>[
                                SizedBox(
                                  height: 4,
                                ),
                                /*StreamBuilder(
                                stream: _assetsAudioPlayer.volume,
                                initialData: AssetsAudioPlayer.DEFAULT_VOLUME,
                                builder: (context, snapshot) {
                                  final double volume = snapshot.data;
                                  return Row(
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    children: <Widget>[
                                      Text("volume : ${((volume * 100).round()) / 100.0}"),
                                      Text(" - "),
                                      Expanded(
                                        child: Slider(
                                          min: AssetsAudioPlayer.MIN_VOLUME,
                                          max: AssetsAudioPlayer.MAX_VOLUME,
                                          value: volume,
                                          onChanged: (value) {
                                            _assetsAudioPlayer.setVolume(value);
                                          },
                                        ),
                                      )
                                    ],
                                  );
                                }),*/ // Ses Açma Kapama Slider

                                Row(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  mainAxisSize: MainAxisSize.max,
                                  children: [
                                    IconButton(
                                      icon: Icon(
                                        _assetsAudioPlayer.shuffle
                                            ? Icons.shuffle
                                            : Icons.format_list_numbered,
                                        size: 25,
                                        color: Colors.white,
                                      ),
                                      onPressed: () {
                                        setState(() {
                                          _assetsAudioPlayer.toggleShuffle();
                                          if (_assetsAudioPlayer.shuffle) {
                                            Fluttertoast.showToast(
                                                msg: "Karışık Çal",
                                                toastLength: Toast.LENGTH_SHORT,
                                                gravity: ToastGravity.CENTER,
                                                timeInSecForIosWeb: 1,
                                                backgroundColor: Colors.black38,
                                                textColor: Colors.white,
                                                fontSize: 16.0);
                                          } else {
                                             Fluttertoast.showToast(
                                                msg: "Sıralı Çal",
                                                toastLength: Toast.LENGTH_SHORT,
                                                gravity: ToastGravity.CENTER,
                                                timeInSecForIosWeb: 1,
                                                backgroundColor: Colors.black38,
                                                textColor: Colors.white,
                                                fontSize: 16.0);
                                          }
                                        });
                                      },
                                    ),
                                    IconButton(
                                      onPressed: () {
                                          _assetsAudioPlayer.previous();
                                          baskinRengiBul();

                                      },
                                      icon: Icon(Icons.skip_previous,
                                          size: 35, color: Colors.white),
                                    ),
                                    StreamBuilder(
                                      stream: _assetsAudioPlayer.isPlaying,
                                      initialData: false,
                                      builder: (BuildContext context,
                                          AsyncSnapshot<bool> snapshot) {
                                        return Align(
                                          alignment: Alignment.center,
                                          child: Container(
                                            width: 75.0,
                                            height: 75.0,
                                            decoration: BoxDecoration(
                                              color: pasifRenk,
                                              shape: BoxShape.circle,
                                              boxShadow: [
                                                BoxShadow(
                                                    color: Color(0xffA22447)
                                                        .withOpacity(.2),
                                                    offset: Offset(0, 0),
                                                    blurRadius: 5,
                                                    spreadRadius: 2)
                                              ],
                                            ),
                                            child: IconButton(
                                              onPressed: () {
                                                _assetsAudioPlayer
                                                    .playOrPause();
                                              },
                                              icon: Icon(
                                                snapshot.data
                                                    ? Icons.pause
                                                    : Icons.play_arrow,
                                                size: 40,
                                                color: Colors.white,
                                              ),
                                            ),
                                          ),
                                        );
                                      },
                                    ),
                                    IconButton(
                                      onPressed: () {
                                         _assetsAudioPlayer.next();
                                         baskinRengiBul();
                                      },
                                        icon: Icon(Icons.skip_next,
                                        size: 35, color: Colors.white),
                                    ),
                                    /*IconButton(
                                    onPressed: () {
                                      _assetsAudioPlayer
                                          .seek(Duration(seconds: 230));
                                    },
                                    icon: Icon(Icons.exposure_plus_2,size:25,color: Colors.white),
                                  ),*/ // Belirli bir saniyeye atlama
                                    IconButton(
                                      icon: Icon(
                                        _assetsAudioPlayer.loop
                                            ? Icons.sync
                                            : Icons.sync_disabled,
                                        size: 25,
                                        color: Colors.white,
                                      ),
                                      onPressed: () {
                                        setState(() {
                                          _assetsAudioPlayer.toggleLoop();
                                          if (_assetsAudioPlayer.loop) {
                                            Fluttertoast.showToast(
                                                msg: "Şarkıyı Tekrarla AÇIK",
                                                toastLength: Toast.LENGTH_SHORT,
                                                gravity: ToastGravity.CENTER,
                                                timeInSecForIosWeb: 1,
                                                backgroundColor: Colors.black38,
                                                textColor: Colors.white,
                                                fontSize: 16.0);
                                          } else {
                                            Fluttertoast.showToast(
                                                msg: "Şarkıyı Tekrarla KAPALI",
                                                toastLength: Toast.LENGTH_SHORT,
                                                gravity: ToastGravity.CENTER,
                                                timeInSecForIosWeb: 1,
                                                backgroundColor: Colors.black38,
                                                textColor: Colors.white,
                                                fontSize: 16.0);
                                          }
                                        });
                                      },
                                    ),
                                  ],
                                ),
                                Expanded(
                                  //
                                  child: Padding(
                                    padding: const EdgeInsets.symmetric(
                                        horizontal: 10),
                                    child: Row(
                                      mainAxisSize: MainAxisSize.max,
                                      mainAxisAlignment:
                                      MainAxisAlignment.spaceBetween,
                                      children: <Widget>[
                                        StreamBuilder(
                                          stream: _assetsAudioPlayer
                                              .currentPosition,
                                          initialData: const Duration(),
                                          builder: (BuildContext context,
                                              AsyncSnapshot<Duration>
                                              snapshot) {
                                            _position = snapshot.data;
                                            return Text(
                                                durationToString(_position));
                                          },
                                        ),
                                        StreamBuilder(
                                          stream: _assetsAudioPlayer.current,
                                          builder: (BuildContext context,
                                              AsyncSnapshot<Playing> snapshot) {
                                            _duration = Duration();

                                            if (snapshot.hasData) {
                                              _duration =
                                                  snapshot.data.audio.duration;
                                            }
                                            return Text(
                                                durationToString(_duration));
                                          },
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                Expanded(
                                  child: StreamBuilder(
                                      stream:
                                      _assetsAudioPlayer.currentPosition,
                                      initialData: const Duration(),
                                      builder: (BuildContext context,
                                          AsyncSnapshot<Duration> snapshot) {
                                        _position = snapshot.data;
                                        return Row(
                                          mainAxisAlignment:
                                          MainAxisAlignment.center,
                                          children: <Widget>[
                                            Expanded(
                                              child: slider(
                                                  _position.inSeconds
                                                      .toDouble(),
                                                  _duration.inSeconds
                                                      .toDouble()),
                                            ),
                                          ],
                                        );
                                      }),
                                ),
                                SizedBox(
                                  height: 8,
                                ),
                                Row(
                                  mainAxisSize: MainAxisSize.max,
                                  mainAxisAlignment:
                                  MainAxisAlignment.spaceBetween,
                                  children: <Widget>[
                                    Expanded(
                                      child: Container(
                                        height: 60,
                                        alignment: Alignment.center,
                                        decoration: BoxDecoration(
                                          color: baskinRenk,
                                        ),
                                      ),
                                    ),
                                    //IconButton(
                                    //  icon: Icon(Icons.highlight_off),
                                    //),
                                  ],
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

String durationToString(Duration duration) {
  String twoDigits(int n) {
    if (n >= 10) return "$n";
    return "0$n";
  }

  String twoDigitMinutes =
  twoDigits(duration.inMinutes.remainder(Duration.minutesPerHour));
  String twoDigitSeconds =
  twoDigits(duration.inSeconds.remainder(Duration.secondsPerMinute));
  return "$twoDigitMinutes:$twoDigitSeconds";
}


run screen 

D/DynamitePackage(32242): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
I/Ads     (32242): This request is sent from a test device.
W/Ads     (32242): Not retrying to fetch app settings
I/flutter (32242): BaskinRengiBul Çalıştı
E/AndroidRuntime(32242): FATAL EXCEPTION: main
E/AndroidRuntime(32242): Process: com.orduwolf.neselicocuksarkilari, PID: 32242
E/AndroidRuntime(32242): java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'
E/AndroidRuntime(32242): 	at j.a.v1.n.a(:76)
E/AndroidRuntime(32242): 	at j.a.v1.o.f(:110)
E/AndroidRuntime(32242): 	at j.a.v1.o.b(:91)
E/AndroidRuntime(32242): 	at j.a.i0.a(:285)
E/AndroidRuntime(32242): 	at j.a.w1.a.a(:26)
E/AndroidRuntime(32242): 	at j.a.b0.a(:109)
E/AndroidRuntime(32242): 	at j.a.a.a(:158)

**Comment by florent37** [comment]
How did you run the app ?
It seems to be obfuscated no ?

at j.a.v1.n.a(:76)

If yes maybe I have some proguard configuration to add

**Comment by stanrisever** [comment]
not release mode?  I ran it in debug mode.

**Comment by stanrisever** [comment]
run screen

E/AndroidRuntime(10429): FATAL EXCEPTION: main
E/AndroidRuntime(10429): Process: com.orduwolf.neselicocuksarkilari, PID: 10429
E/AndroidRuntime(10429): java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'
E/AndroidRuntime(10429): 	at j.a.v1.n.a(:76)
E/AndroidRuntime(10429): 	at j.a.v1.o.f(:110)
E/AndroidRuntime(10429): 	at j.a.v1.o.b(:91)
E/AndroidRuntime(10429): 	at j.a.i0.a(:285)
E/AndroidRuntime(10429): 	at j.a.w1.a.a(:26)
E/AndroidRuntime(10429): 	at j.a.b0.a(:109)
E/AndroidRuntime(10429): 	at j.a.a.a(:158)
E/AndroidRuntime(10429): 	at j.a.d.a(:54)
E/AndroidRuntime(10429): 	at j.a.c.a(:1)
E/AndroidRuntime(10429): 	at j.a.d.a(:47)
E/AndroidRuntime(10429): 	at j.a.c.a(:1)
E/AndroidRuntime(10429): 	at f.a.a.a.f.a(:151)
E/AndroidRuntime(10429): 	at f.a.a.a.a.a(:335)
E/AndroidRuntime(10429): 	at h.a.b.a.i$a.a(:226)
E/AndroidRuntime(10429): 	at io.flutter.embedding.engine.e.b.a(:85)
E/AndroidRuntime(10429): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:631)
E/AndroidRuntime(10429): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(10429): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/AndroidRuntime(10429): 	at android.os.Looper.loop(Looper.java:160)
E/AndroidRuntime(10429): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(10429): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10429): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(10429): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process (10429): Sending signal. PID: 10429 SIG: 9

**Comment by florent37** [comment]
I think I forgot to add coroutine core inside the Android lib, I'll add it today & send you a new version

**Comment by florent37** [comment]
I have 
```
 implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.6'
 implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.6'
```

in the android project :/ 

I try to reproduce what's here

**Comment by florent37** [comment]
https://github.com/Kotlin/kotlinx.coroutines/issues/1606

**Comment by florent37** [comment]
can you tell me in your android/build.gradle what's in this line 

```
 classpath 'com.android.tools.build:gradle:X.X.X' <---
```

and your android/gradle/wrapper/gradle-wrapper.properties

```
distributionUrl=https\://services.gradle.org/distributions/gradle-X.X.X-all.zip
```

**Comment by florent37** [comment]
try to add this in your proguard-rules.pro please

```
-keepclassmembernames class kotlinx.** {
    volatile <fields>;
}
-keepnames class kotlinx.** { *; }
```

**Comment by stanrisever** [comment]
android / build.gradle

classpath 'com.android.tools.build:gradle:3.5.0'

android / gradle / wrapper / gradle-wrapper.properties

distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip

**Comment by stanrisever** [comment]
> bunu proguard-rules.pro dosyasına eklemeyi deneyin lütfen
> 
> ```
> -keepclassmembernames class kotlinx.** {
>     volatile <fields>;
> }
> -keepnames class kotlinx.** { *; }
> ```

i don't know how to do this

**Comment by florent37** [comment]
you have a proguard rules into your android project, just add those lines inside

**Comment by stanrisever** [comment]
Thank you very much for your support. i got rid of the error right now

**Comment by florent37** [comment]
:)

**Comment by azabost** [comment]
> try to add this in your proguard-rules.pro please
> 
> ```
> -keepclassmembernames class kotlinx.** {
>     volatile <fields>;
> }
> -keepnames class kotlinx.** { *; }
> ```

@florent37 But why would anyone need to do that? I though the library already includes all the required ProGuard rules to make sure it doesn't get deleted, doesn't it?

**Comment by florent37** [comment]
It's a r8 rule for coroutine. I don't know why but it seems to not be recursively imported  while fetching the Android project

**Comment by florent37** [comment]
Maybe I have a custom thing to add but I don't know what
