### ISSUE TITLE
Local Assets with Spaces fail to load

### ISSUE THREAD

**Issue by benjlin** [florent37/Flutter-AssetsAudioPlayer#250]
**Flutter Version**

My version : Flutter 1.19.0-4.2.pre • channel beta •

**Lib Version**

My version : ^2.0.6+3

**Platform (Android / iOS / web) + version**

Platform :  Android (but probably others)

**Describe the bug**

When an asset file contains a space in the file name e.g "song 1.mp3" the plugin will crash. 
this is related to issues in the core flutter framework.

https://github.com/flutter/flutter/issues/47705
https://github.com/flutter/flutter/issues/42584

```D/PlayerImplem( 8487): trying to open with exoplayer(Default)
W/m.example.musi( 8487): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl( 8487): Init 56cdd26 [ExoPlayerLib/2.11.4] [bonito, Pixel 3a XL, Google, 29]
D/PlayerImplem( 8487): failed to open with exoplayer(Default)
I/ExoPlayerImpl( 8487): Release 56cdd26 [ExoPlayerLib/2.11.4] [bonito, Pixel 3a XL, Google, 29] [goog.exo.core]
D/PlayerImplem( 8487): trying to open with exoplayer(HLS)
D/PlayerImplem( 8487): trying to open with exoplayer(DASH)
D/PlayerImplem( 8487): trying to open with exoplayer(SmoothStreaming)
D/PlayerImplem( 8487): trying to open with native mediaplayer
D/PlayerImplem( 8487): failed to open with native mediaplayer
V/MediaPlayer( 8487): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 8487): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/System.err( 8487): com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$NoPlayerFoundException
W/System.err( 8487): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:68)
W/System.err( 8487): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:83)
I/chatty  ( 8487): uid=10261(com.example.music) identical 3 lines
W/System.err( 8487): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:83)
W/System.err( 8487): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder.findWorkingPlayer(PlayerFinder.kt:92)
W/System.err( 8487): 	at com.github.florent37.assets_audio_player.Player$open$1.invokeSuspend(Player.kt:176)
W/System.err( 8487): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err( 8487): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
W/System.err( 8487): 	at android.os.Handler.handleCallback(Handler.java:883)
W/System.err( 8487): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err( 8487): 	at android.os.Looper.loop(Looper.java:214)
W/System.err( 8487): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err( 8487): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 8487): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err( 8487): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/flutter ( 8487): PlatformException(OPEN, null, null)
E/flutter ( 8487): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(OPEN, null, null)
```

**Comment by benjlin** [comment]
below is some example code to show off the problem, this is based off the assumption that you have to files in the assets folder "Song1.mp3" and "Song 1.mp3" that both files are actually the same functional mp3 file just with different names

``` 
void startSongWorking() {
	startLocalAsset("Song1.mp3"); // Would successfully play the asset
}

void startSongNotWorking() {
	startLocalAsset("Song 1.mp3"); // Would result in the above error
}

void startLocalAsset(String song) {
    assetsAudioPlayer.open(
      Audio("assets/audios/" + song)
    );
  }```

**Comment by florent37** [comment]
I don't know how to fix it, because I open the song from the android platform, using 

```
flutterAssets.getAssetFilePathByName(assetAudioPath)
```

I'll try to add a space to see how android handle it

**Comment by florent37** [comment]
I found how to fix it

```kotlin
val p = assetAudioPath!!.replace(" ", "%20")
val path = if (assetAudioPackage.isNullOrBlank()) {
       flutterAssets.getAssetFilePathByName(p)
} else {
       flutterAssets.getAssetFilePathByName(p, assetAudioPackage)
}
val assetDataSource = AssetDataSource(context)
assetDataSource.open(DataSpec(Uri.fromFile(File(path))))
```

I pushed a `2.0.7+5` can you try ?

**Comment by benjlin** [comment]
I can confirm that spaces in are working correctly in 2.0.7+8. Thank you

**Comment by florent37** [comment]
:)

**Comment by chearuno** [comment]
Not working on IOS. Android is working fine. tested on assets_audio_player: ^2.0.10

**Comment by Demircivi** [comment]
This is still the case for me on 3.0.5 on iOS.
