### ISSUE TITLE
updateCurrentAudioNotification: Unhandled exception: invalid argument: instance of ' Audio '

### ISSUE THREAD

**Issue by DomingoMG** [florent37/Flutter-AssetsAudioPlayer#267]
**Flutter Version**

My version : 1.90.0-4.2.pre

**Lib Version**

My version : 

**Platform (Android / iOS / web) + version**

Platform : Android

**Describe the bug**
I am trying to update the notification information and I am getting this error, I don't know what I am doing wrong.
I am listening to a radio station and when I update the information in the notification it appears: E / flutter (29689): [ERROR: flutter / lib / ui / ui_dart_state.cc (166)] Unhandled exception: invalid argument: instance of ' Audio '

**Small code to reproduce**

Dart:
```
try {
        Map<String, dynamic> data = json.decode(utf8.decode(response.bodyBytes));
        Provider.of<AssetsAudioPlayer>(context, listen: false).updateCurrentAudioNotification(
            metas: Metas(
            title: 'Las Palmas 94.1 FM',
            artist: '${data['title']} - ${data['artist']}',
            image:  MetasImage.asset('assets/company/logo.png') 
          ),
          showNotifications: true
        );
      }catch(e){
        print('ERROR INFO');
      }
```

```
E/flutter (29689): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Invalid argument: Instance of 'Audio'
E/flutter (29689): #0      StandardMessageCodec.writeValue 
package:flutter/…/services/message_codecs.dart:392
E/flutter (29689): #1      StandardMessageCodec.writeValue.<anonymous closure> 
package:flutter/…/services/message_codecs.dart:389
E/flutter (29689): #2      _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (29689): #3      StandardMessageCodec.writeValue 
package:flutter/…/services/message_codecs.dart:387
E/flutter (29689): #4      StandardMethodCodec.encodeMethodCall 
package:flutter/…/services/message_codecs.dart:524
E/flutter (29689): #5      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:151
E/flutter (29689): #6      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:332
E/flutter (29689): #7      AssetsAudioPlayer.updateCurrentAudioNotification 
package:assets_audio_player/src/assets_audio_player.dart:1049
E/flutter (29689): #8      _HomePageState.fetchData 
package:radiofaycan/…/pages/HomePage.dart:44
E/flutter (29689): <asynchronous suspension>
E/flutter (29689): #9      _HomePageState.fetchMetadata.<anonymous closure> 
package:radiofaycan/…/pages/HomePage.dart:34
E/flutter (29689): #10     _rootRunUnary  (dart:async/zone.dart:1198:47)
E/flutter (29689): #11     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (29689): #12     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7)

```

**Comment by florent37** [comment]
I think I fixed it, it was a small issue :) can you try `2.0.7+8` ?
