### ISSUE TITLE
How to update the path of a song？

### ISSUE THREAD

**Issue by liuchuancong** [florent37/Flutter-AssetsAudioPlayer#278]
```
_player.onErrorDo = (handler){
  handler.player.open(
      handler.playlist.copyWith(
        startIndex: handler.playlistIndex
      ),
      seek: handler.currentPosition
  );
};
```
The song path  has expired,  how can i update this path ?

**Comment by liuchuancong** [comment]
```
        handler.player.playlist.replaceAt(
            handler.playlistIndex,
            (oldAudio) =>
                new audioPlayer.Audio.network(path, metas: oldAudio.metas));
```

**Comment by liuchuancong** [comment]
Not work!

**Comment by liuchuancong** [comment]
```
I/ExoPlayerImpl( 8015): Init 13f3b52 [ExoPlayerLib/2.11.4] [dipper, MI 8, Xiaomi, 29]
E/ExoPlayerImplInternal( 8015): Source error
E/ExoPlayerImplInternal( 8015):   com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
E/ExoPlayerImplInternal( 8015):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
E/ExoPlayerImplInternal( 8015):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal( 8015):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:956)
E/ExoPlayerImplInternal( 8015):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
E/ExoPlayerImplInternal( 8015):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 8015):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 8015):       at java.lang.Thread.run(Thread.java:919)
D/PLAYER  ( 8015): XXXX onPlayerError XXXX
```

**Comment by florent37** [comment]
for your case you can use the "replaceAt" 

1. create a playlist
2. add the audio into your playlist
3. if error, use "replaceAt" + index of your audio, & using copyWith on your old audio

```
playlist.replaceAt(0, (oldAudio) => oldAudio.copyWith(path: NEW_PATH));
```

**Comment by liuchuancong** [comment]
How  can i get response err code at multiple places? like: player.next(), player.play(),player.perv(),player.playAtIndex(),  
I think  i need a callback to solve this problem,instead of  `try catch`

**Comment by liuchuancong** [comment]
Hi,my dear firend  @florent37 

when the current song has finished to play.

![image](https://user-images.githubusercontent.com/36957912/87917988-5b1a7b00-caa8-11ea-90f3-6921ddf739e8.png)
![image](https://user-images.githubusercontent.com/36957912/87918013-62da1f80-caa8-11ea-8ed8-b96cbedff59c.png)

or  Notifications next,etc. 
 
AudioPlayer just stop!

I can't received  error callback.

```
try {
      await assetsAudioPlayer.previous(keepLoopMode: true);
    } on PlatformException catch (err) {
      //err  ->  just work
    } catch (err) {
      // other types of Exceptions
    }
```
`AudioInstance().init();`
```
init() {
    assetsAudioPlayer.onErrorDo = (handler) {
      print('---------------------onErrorDo------------------');
    };
  }
```
always not work
