### ISSUE TITLE
Failed assertion: !navigator._debugLocked': is not true.

### ISSUE THREAD

**Issue by DomingoMG** [florent37/Flutter-AssetsAudioPlayer#288]
**Flutter Version**

My version : 1.19.0-4.3.pre

**Lib Version**

My version :   assets_audio_player: ^2.0.8+2

**Platform (Android / iOS / web) + version**
Platform : Android

**Describe the bug**
I am listening to a radio station while browsing the application and when I click on TextFormField it throws an exception and stops streaming. I don't know if I'm doing something wrong.

![Screenshot_1594829284](https://user-images.githubusercontent.com/36201422/87568853-37c58980-c6be-11ea-905d-93be6de55025.png)

**Small code to reproduce**

``` Debug Console
E/flutter (30991): #2      _RouteEntry.handlePush.<anonymous closure> 
package:flutter/…/widgets/navigator.dart:2364
E/flutter (30991): #3      TickerFuture.whenCompleteOrCancel.thunk 
package:flutter/…/scheduler/ticker.dart:399
E/flutter (30991): #4      _rootRunUnary  (dart:async/zone.dart:1198:47)
E/flutter (30991): #5      _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (30991): #6      _FutureListener.handleValue  (dart:async/future_impl.dart:143:18)
E/flutter (30991): #7      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:696:45)
E/flutter (30991): #8      Future._propagateToListeners  (dart:async/future_impl.dart:725:32)
E/flutter (30991): #9      Future._completeWithValue  (dart:async/future_impl.dart:529:5)
E/flutter (30991): #10     Future._asyncCompleteWithValue.<anonymous closure>  (dart:async/future_impl.dart:567:7)
E/flutter (30991): #11     _rootRun  (dart:async/zone.dart:1190:13)
E/flutter (30991): #12     _CustomZone.run  (dart:async/zone.dart:1093:19)
E/flutter (30991): #13     _CustomZone.runGuarded  (dart:async/zone.dart:997:7)
E/flutter (30991): #14     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23)
E/flutter (30991): #15     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)
E/flutter (30991): #16     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)
E/flutter (30991):
I/OMXClient(30991): IOmx service obtained
I/ACodec  (30991): codec does not support config priority (err -2147483648)
I/xel.radiofayca(30991): Background concurrent copying GC freed 32444(1782KB) AllocSpace objects, 23(1220KB) LOS objects, 49% free, 3514KB/7029KB, paused 562us total 127.416ms
```

**Comment by florent37** [comment]
hi, thanks for the issue, can you send me a full sample code to reproduce this error please ?

**Comment by kalismeras61** [comment]
It is not a pluging itself issue. Closed.
