### ISSUE TITLE
MediaButtonReceiver component may not be null

### ISSUE THREAD

**Issue by yy1300326388** [florent37/Flutter-AssetsAudioPlayer#297]
**Flutter Version**

My version : 

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale
    zh-Hans-CN)
    • Flutter version 1.17.5 at .../sdk/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
```

**Lib Version**

My version : 2.0.8+2

**Platform (Android / iOS / web) + version**

Platform : Android 4.4

**Describe the bug**

MediaButtonReceiver component may not be null

**Log**

```
D/dalvikvm: GC_FOR_ALLOC freed 412K, 12% free 3734K/4240K, paused 2ms, total 3ms
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.banjixiaoguanjia.app, PID: 2589
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.banjixiaoguanjia.app/com.banjixiaoguanjia.app.MainActivity}: java.lang.IllegalArgumentException: MediaButtonReceiver component may not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalArgumentException: MediaButtonReceiver component may not be null
        at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.<init>(MediaSessionCompat.java:2232)
        at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi18.<init>(MediaSessionCompat.java:3413)
        at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi19.<init>(MediaSessionCompat.java:3497)
        at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:574)
        at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:530)
        at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:494)
        at com.github.florent37.assets_audio_player.notification.MediaButtonsReceiver$Companion.getMediaSessionCompat(MediaButtonsReceiver.kt:21)
        at com.github.florent37.assets_audio_player.notification.MediaButtonsReceiver.<init>(MediaButtonsReceiver.kt:56)
        at com.github.florent37.assets_audio_player.AssetsAudioPlayer.register(AssetsAudioPlayerPlugin.kt:139)
        at com.github.florent37.assets_audio_player.AssetsAudioPlayerPlugin.onAttachedToEngine(AssetsAudioPlayerPlugin.kt:56)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.add(FlutterEnginePluginRegistry.java:133)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:19)
        at com.banjixiaoguanjia.app.MainActivity.configureFlutterEngine(MainActivity.kt:15)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:178)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:409)
        at com.banjixiaoguanjia.app.MainActivity.onCreate(MainActivity.kt:19)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 

```

**Comment by florent37** [comment]
fixed, can you try `2.0.8+4` ?
