### ISSUE TITLE
Crash reports, Android, Glide

### ISSUE THREAD

**Issue by pro100svitlo** [florent37/Flutter-AssetsAudioPlayer#302]
Hello.
I am using `assets_audio_player: 2.0.8+2` version of the library and I face crash reports on firebase with the next logs:

```
Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.example/com.github.florent37.assets_audio_player.notification.NotificationService (has extras) }: app is in background uid UidRecord{d6c790b u0a86 LAST bg:+1m6s535ms idle change:idle procs:1 seq(327,327,327)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1616)
       at android.app.ContextImpl.startService(ContextImpl.java:1571)
       at android.content.ContextWrapper.startService(ContextWrapper.java:669)
       at com.github.florent37.assets_audio_player.notification.NotificationManager.a(NotificationManager.java:60)
       at com.github.florent37.assets_audio_player.Player.d(Player.java:41)
       at com.github.florent37.assets_audio_player.Player.a(Player.java:5)
       at com.github.florent37.assets_audio_player.Player.pause(Player.java:38)
       at com.github.florent37.assets_audio_player.Player.a(Player.java:40)
       at com.github.florent37.assets_audio_player.AssetsAudioPlayer$stopWhenCallListener$1.onPhoneStateChanged(AssetsAudioPlayer.java:31)
       at com.github.florent37.assets_audio_player.stopwhencall.StopWhenCall.a(StopWhenCall.java:23)
       at com.github.florent37.assets_audio_player.stopwhencall.StopWhenCallAudioFocus$listener$1.invoke(StopWhenCallAudioFocus.java:17)
       at com.github.florent37.assets_audio_player.stopwhencall.StopWhenCallAudioFocus$listener$1.invoke(StopWhenCallAudioFocus.java:6)
       at com.github.florent37.assets_audio_player.stopwhencall.StopWhenCallAudioFocus$sam$i$android_media_AudioManager_OnAudioFocusChangeListener$0.onAudioFocusChange(StopWhenCallAudioFocus.java:6)
       at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2496)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by florent37** [comment]
fixed, will be send in next release
