### ISSUE TITLE
[Critical] MetasImage.asset is now broken in Flutter 1.22.0 - Android - java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference

### ISSUE THREAD

**Issue by ilkercankaya** [florent37/Flutter-AssetsAudioPlayer#371]
**Flutter Version**

My version : Flutter 1.22.0 • channel stable

**Lib Version**

My version : assets_audio_player: ^2.0.10

Platform :  Android

**Bug:**

With the latest flutter SDK upgrade to 1.22.0 MetasImage.asset is comletely broken. When used, Android Plugin throws the exception below.

> 'java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference'

I believe this is due to changes made with "Android embedding API" under flutter version 1.22.0. To reproduce this just try to use the lib with a MetasImage.asset as a Metas parameter.

I hope this could get fixed soon as I want to ship an app with  MetasImage.asset in it. 

Thank you!

**Small code to reproduce**

```dart
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State {
  
  final AssetsAudioPlayer _assetsAudioPlayer = AssetsAudioPlayer();

  @override
  Widget build(BuildContext context) {
  AssetsAudioPlayer.newPlayer().open(
      Audio(
        "images/myAudio.wav",
        metas: Metas(
          title: "Country",
          artist: "Florent Champigny",
          album: "CountryAlbum",
          image: MetasImage.asset(
              "images/myImage.jpg"), //can be MetasImage.network
        ),
      ),
      showNotification: true,
    );

    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            child: Text("open"),
            onPressed: () {
              //open code here
            }
          ),
        ),
      ),
    );
  }
}
```

Full Debug:
```
Launching lib\main.dart on SM N970F in debug mode...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:51372/3GrwgQJa9G8=/ws
W/mple.audio_tes(31040): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl(31040): Init ff72eb3 [ExoPlayerLib/2.11.4] [d1, SM-N970F, samsung, 29]
W/AudioCapabilities(31040): Unsupported mime audio/x-ima
W/AudioCapabilities(31040): Unsupported mime audio/mpeg-L1
W/AudioCapabilities(31040): Unsupported mime audio/mpeg-L2
W/AudioCapabilities(31040): Unsupported mime audio/x-ms-wma
W/AudioCapabilities(31040): Unsupported mime audio/x-ape
W/VideoCapabilities(31040): Unsupported mime video/wvc1
W/VideoCapabilities(31040): Unsupported mime video/avc-wfd
I/chatty  (31040): uid=10488(com.example.audio_test) ExoPlayerImplIn identical 1 line
W/VideoCapabilities(31040): Unsupported mime video/avc-wfd
W/VideoCapabilities(31040): Unsupported mime video/hevc-wfd
W/VideoCapabilities(31040): Unsupported mime video/hevc-wfd
W/VideoCapabilities(31040): Unsupported mime video/mp43
W/VideoCapabilities(31040): Unrecognized profile/level 1/32 for video/mp4v-es
W/VideoCapabilities(31040): Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities(31040): Unrecognized profile/level 32768/64 for video/mp4v-es
W/VideoCapabilities(31040): Unsupported mime video/wvc1
W/VideoCapabilities(31040): Unsupported mime video/x-ms-wmv7
W/VideoCapabilities(31040): Unsupported mime video/x-ms-wmv8
D/CCodec  (31040): allocate(c2.android.raw.decoder)
I/Codec2Client(31040): Available Codec2 services: "default" "software"
I/Codec2Client(31040): Creating a Codec2 client to service "default"
I/Codec2Client(31040): Client to Codec2 service "default" created
I/CCodec  (31040): setting up 'default' as default (vendor) store
I/Codec2Client(31040): Creating a Codec2 client to service "default"
I/Codec2Client(31040): Client to Codec2 service "default" created
E/Codec2Client(31040): createComponent(c2.android.raw.decoder) -- call failed: NOT_FOUND.
I/Codec2Client(31040): Creating a Codec2 client to service "software"
I/Codec2Client(31040): Client to Codec2 service "software" created
I/CCodec  (31040): Created component [c2.android.raw.decoder]
D/CCodecConfig(31040): read media type: audio/raw
D/ReflectedParamUpdater(31040): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(31040): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(31040): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(31040): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(31040): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(31040): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(31040): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig(31040): query failed after returning 8 values (BAD_INDEX)
D/CCodecConfig(31040): c2 config is Dict {
D/CCodecConfig(31040):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(31040):   c2::u32 input.buffers.max-size.value = 65536
D/CCodecConfig(31040):   c2::u32 input.delay.value = 0
D/CCodecConfig(31040):   string input.media-type.value = "audio/raw"
D/CCodecConfig(31040):   string output.media-type.value = "audio/raw"
D/CCodecConfig(31040):   c2::u32 raw.channel-count.value = 2
D/CCodecConfig(31040):   c2::u32 raw.pcm-encoding.value = 0
D/CCodecConfig(31040):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig(31040): }
D/CCodecConfig(31040): config failed => CORRUPTED
W/Codec2Client(31040): query -- param skipped: index = 1107298332.
D/CCodec  (31040): client requested max input size 35280, which is smaller than what component recommended (65536); overriding with component recommendation.
W/CCodec  (31040): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  (31040): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (31040):   int32_t channel-count = 2
D/CCodec  (31040):   int32_t max-input-size = 65536
D/CCodec  (31040):   string mime = "audio/raw"
D/CCodec  (31040):   int32_t pcm-encoding = 2
D/CCodec  (31040):   int32_t sample-rate = 44100
D/CCodec  (31040):   int64_t durationUs = 0
D/CCodec  (31040): } and output: AMessage(what = 0x00000000) = {
D/CCodec  (31040):   int32_t channel-count = 2
D/CCodec  (31040):   string mime = "audio/raw"
D/CCodec  (31040):   int32_t pcm-encoding = 2
D/CCodec  (31040):   int32_t sample-rate = 44100
D/CCodec  (31040): }
W/Codec2Client(31040): query -- param skipped: index = 1342179345.
W/Codec2Client(31040): query -- param skipped: index = 2415921170.
D/CCodecBufferChannel(31040): [c2.android.raw.decoder#830] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
I/CCodecBufferChannel(31040): [c2.android.raw.decoder#830] Created output block pool with allocatorID 16 => poolID 987 - OK
D/CCodecBufferChannel(31040): [c2.android.raw.decoder#830] Configured output block pool ids 987 => OK
E/C2AllocatorIon(31040): >>>SEC mapUsage Mapper1 1
E/ion     (31040): ioctl c0044901 failed with code -1: Not a typewriter
E/C2AllocatorIon(31040): >>>SEC mapUsage	0, 1
D/AudioTrack(31040): setVolume(1.000000, 1.000000) pid : 31040
W/System.err(31040): java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
W/System.err(31040): 	at io.flutter.embedding.engine.loader.FlutterLoader.fullAssetPathFrom(FlutterLoader.java:355)
W/System.err(31040): 	at io.flutter.embedding.engine.loader.FlutterLoader.getLookupKeyForAsset(FlutterLoader.java:336)
W/System.err(31040): 	at com.github.florent37.assets_audio_player.notification.ImageDownloader$getBitmap$2.invokeSuspend(ImageDownloader.kt:61)
W/System.err(31040): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err(31040): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
W/System.err(31040): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
W/System.err(31040): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
W/System.err(31040): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
W/System.err(31040): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
D/AudioTrack(31040): getTimestamp_l(3551): device stall time corrected using current time 127341696400187
D/AudioTrack(31040): getTimestamp_l(3551): stale timestamp time corrected, currentTimeNanos: 127265218959934 < limitNs: 127341525352380 < mStartNs: 127341605352380
W/AudioTrack(31040): getTimestamp_l(3551): retrograde timestamp time corrected, 127341525352380 < 127341696400187
I/ViewRootImpl@468f36c[MainActivity](31040): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(31040): prepareNavigationBarInfo() DecorView@e38e340[MainActivity]
D/InputMethodManager(31040): getNavigationBarColor() -855310
D/BufferPoolAccessor(31040): bufferpool2 0x71f58a9a20 : 5(327680 size) total buffers - 4(262144 size) used buffers - 0/5 (recycle/alloc) - 4/119 (fetch/transfer)
D/BufferPoolAccessor(31040): bufferpool2 0x71f58a9a20 : 5(327680 size) total buffers - 4(262144 size) used buffers - 0/5 (recycle/alloc) - 4/231 (fetch/transfer)
D/BufferPoolAccessor(31040): bufferpool2 0x71f58a9a20 : 5(327680 size) total buffers - 4(262144 size) used buffers - 0/5 (recycle/alloc) - 4/343 (fetch/transfer)
D/BufferPoolAccessor(31040): bufferpool2 0x71f58a9a20 : 5(327680 size) total buffers - 4(262144 size) used buffers - 0/5 (recycle/alloc) - 4/455 (fetch/transfer)
I/ExoPlayerImpl(31040): Release ff72eb3 [ExoPlayerLib/2.11.4] [d1, SM-N970F, samsung, 29] [goog.exo.core]
W/Codec2Client(31040): query -- param skipped: index = 1342179345.
W/Codec2Client(31040): query -- param skipped: index = 2415921170.
I/MediaCodec(31040): Codec shutdown complete
```

**Comment by lawkeen** [comment]
Same to me, did you fix this?

**Comment by ilkercankaya** [comment]
@lawkeen No, I switched to just_audio, the seekbar on Android was also lagging sometimes when it was seeked. The lib felt unpolished so I decided to make my own in the future.

**Comment by RickVM** [comment]
Why was this closed? Although I haven't checked in for a due to other priorities, I had the same problem and would like a fix

**Comment by kalismeras61** [comment]
@RickVM, which version are you using ? Can you try using this plugin like below.

assets_audio_player:
git:
url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
ref: b49a4360f6a7f182d4a6e23ebcdbf43ad570913b

**Comment by kashishkhullar** [comment]
I tested this out. With Local assets files the image is not shown and throws the error mentioned above. However it works for network files. 

`MetasImage.network("file_url")` works as expected but with the following error

```
W/Glide   (29911): Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored

I/System.out(29911): java.lang.Exception: no null on AndroidManifest.xmljava.lang.Exception: no null on AndroidManifest.xmljava.lang.Exception: no null on AndroidManifest.xmljava.lang.Exception: no null on AndroidManifest.xmljava.lang.Exception: no null on AndroidManifest.xmljava.lang.Exception: no null on AndroidManifest.xmljava.lang.Exception: no null on AndroidManifest.xmljava.lang.Exception: no null on AndroidManifest.xmljava.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object referencejava.lang.Exception: no null on AndroidManifest.xmljava.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object referencejava.lang.Exception: no null on AndroidManifest.xmljava.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object referencejava.lang.Exception: no null on AndroidManifest.xmljava.lang.Exception: no null on AndroidManifest.xmljava.lang.Exception: no null on AndroidManifest.xmljava.lang.Exception: no null on AndroidManifest.xmljava.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object referencejava.lang.Exception: no null on AndroidManifest.xml[okhttp]:check permission begin!

```

**Comment by kalismeras61** [comment]
What ia your flutter version ?

Can you check this ?

https://github.com/transistorsoft/flutter_background_fetch/issues/160#issuecomment-716694762

**Comment by kashishkhullar** [comment]
i'm using v1.22.4

**Comment by kalismeras61** [comment]
Can you check this steps ? 

https://github.com/transistorsoft/flutter_background_fetch/issues/160#issuecomment-716694762

**Comment by kashishkhullar** [comment]
Tried the solutions mentioned in the thread but the I am still getting the same error and the MetaImage.asset is still not working?
Will upgrading the flutter version fix this?

**Comment by kalismeras61** [comment]
Fixed.
