### ISSUE TITLE
Notification is not showing Album Image for Local Audio Files

### ISSUE THREAD

**Issue by rajeshjeshar** [florent37/Flutter-AssetsAudioPlayer#384]
**Flutter 1.20.2 stable**

My version : 

**assets_audio_player: ^2.0.12**

My version : 

**Android 10**

Platform : Android

**Audio files from Url are showing Album arts in notification,but while using `flutter_audio_query: ^0.3.5+6` to use with assetsauidoplayer,the Locally downloaded song album images are not showing in notifications**

Album art is showing inside app successfully by this code:

```
Widget leadingWidget() {
    return SizedBox(
      width: 42,
      height: 42,
      child: FutureBuilder<Uint8List>(
        initialData: Uint8List(0),
        future: _audioQuery.getArtwork(
          type: ResourceType.SONG,
          id: widget.song.id,
          size: Size(100, 100)),
          builder: (context, snapshot) {
          bool noImgFound = snapshot.data.isEmpty;
          return Container(
              height: 42,
              width: 42,
               decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(6),
                color: widget.selected ? Colorz.primaryColor : Colors.blue.shade400,
                image: noImgFound? null: DecorationImage(image: MemoryImage(snapshot.data),fit: BoxFit.cover),
              ),
            );
          }),
    );
  }
```

**Small code to convert Playable Audio file from the SongInfo file from **flutter_audio_query** plugin**

```  
Audio songToAudio(SongInfo song)=>Audio.file(song.filePath,
                  metas: Metas(
                    title: song.title,
                    album: song.album,
                    artist: song.artist,
                    id: song.id,
                    image: MetasImage.file(song.filePath),
                  ));
```
![e2a1b9a1-b6f4-4347-9380-0e15ee627b3d](https://user-images.githubusercontent.com/39165538/97435723-d6f94e80-1946-11eb-971d-f6e767cf1237.jpg)

**Comment by stanrisever** [comment]
The same problem started with version 2.0.12 with me

**Comment by moosalim** [comment]
I have the same issue

**Comment by stanrisever** [comment]
Has anyone found a solution?

**Comment by moosalim** [comment]
Until this bug is fixed, I suggest you use image from internet sources i.e MetasImage.network instead of MetasImage.file or MetasImage.asset

**Comment by vemla-solutions** [comment]
I use assets_audio_player: ^2.0.13+6 and the error is still present.
When MetasImage.network() is used the image is displayed fine.

But MetsImage.asset() is not displaying an image and produces an error:
W/System.err(21729): java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
W/System.err(21729): 	at io.flutter.embedding.engine.loader.FlutterLoader.fullAssetPathFrom(FlutterLoader.java:355)
W/System.err(21729): 	at io.flutter.embedding.engine.loader.FlutterLoader.getLookupKeyForAsset(FlutterLoader.java:336)
W/System.err(21729): 	at com.github.florent37.assets_audio_player.notification.ImageDownloader$getBitmap$2.invokeSuspend(ImageDownloader.kt:61)
W/System.err(21729): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err(21729): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/System.err(21729): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
W/System.err(21729): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W/System.err(21729): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
W/System.err(21729): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Is there a fix for this in order to display an image from the local image file?
Thank you!
