### ISSUE TITLE
 java.lang.NoSuchMethodError: No virtual method createNotificationChannel(Landroid/app/NotificationChannel;)V in class Landroidx/core/app/NotificationManagerCompat; or its super classes (declaration of 'androidx.core.app.NotificationManagerCompat' appears in /data/app/.../base.apk!classes2.dex

### ISSUE THREAD

**Issue by dharshatharan** [florent37/Flutter-AssetsAudioPlayer#428]
**Flutter Version**

My version : 1.22.5

**Lib Version**

My version : assets_audio_player: ^2.0.13+1

**Platform (Android / iOS / web) + version**

Platform : Android 10

**Describe the bug**

When ```showNotification``` is set to ```true``` while opening an audio/playlist, my app closes with the following error message. I am not sure if this is a versioning issue:

```
E/AndroidRuntime(21079): java.lang.NoSuchMethodError: No virtual method createNotificationChannel(Landroid/app/NotificationChannel;)V in class Landroidx/core/app/NotificationManagerCompat; or its super classes (declaration of 'androidx.core.app.NotificationManagerCompat' appears in /data/app/.../base.apk!classes2.dex)
E/AndroidRuntime(21079): 	at com.github.florent37.assets_audio_player.notification.NotificationService.createNotificationChannel(NotificationService.kt:323)
E/AndroidRuntime(21079): 	at com.github.florent37.assets_audio_player.notification.NotificationService.displayNotification(NotificationService.kt:213)
E/AndroidRuntime(21079): 	at com.github.florent37.assets_audio_player.notification.NotificationService.access$displayNotification(NotificationService.kt:27)
E/AndroidRuntime(21079): 	at com.github.florent37.assets_audio_player.notification.NotificationService$displayNotification$1.invokeSuspend(NotificationService.kt:141)
E/AndroidRuntime(21079): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(21079): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
E/AndroidRuntime(21079): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(21079): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(21079): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(21079): 	at android.app.ActivityThread.main(ActivityThread.java:7860)
E/AndroidRuntime(21079): 	at java.lang.reflect.Method.invoke(Native Method)
I/Process (21079): Sending signal. PID: 21079 SIG: 9
Lost connection to device.
Exited (sigterm)
```

**Small code to reproduce**

```dart
_queuePlaylist = Playlist(audios: _audioQueue, startIndex: startIndex);
await _audioPlayer.open(
  queuePlaylist,
  seek: playPosition,
  autoStart: false,
  showNotification: true,
);
```

Flutter doctor -v

```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1256], locale en-CA)
    • Flutter version 1.22.5 at C:\Users\Dharsh\flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Dharsh\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Dharsh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

**Comment by kalismeras61** [comment]
Please use latest commit . Still have problem, please reopen.

**Comment by anasssanba1** [comment]
this issue should be reopen why you close this issue?
