### ISSUE TITLE
Can't play songs in release mode

### ISSUE THREAD

**Issue by BilenAhmet** [florent37/Flutter-AssetsAudioPlayer#487]
İts work in debug mode. But when I build an release APK it doesn't work.

**Comment by BilenAhmet** [comment]
crash log 

> C:\Users\Administrator>adb logcat -b crash
> adb server version (41) doesn't match this client (36); killing...
> * daemon started successfully *
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime: FATAL EXCEPTION: main
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime: Process: com.example.music, PID: 30418
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime: java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android' and ensure it has the same version as 'kotlinx-coroutines-core'
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at f.a.w1.p.a(Unknown Source:4)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at f.a.w1.q.h(Unknown Source:55)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at f.a.w1.q.b(Unknown Source:0)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at f.a.w1.e.a(Unknown Source:16)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at f.a.x1.a.a(Unknown Source:15)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at f.a.x1.a.a(Unknown Source:5)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at f.a.d0.a(Unknown Source:41)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at f.a.a.a(Unknown Source:3)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at f.a.d.a(Unknown Source:22)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at f.a.c.a(Unknown Source:0)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at f.a.d.a(Unknown Source:12)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at f.a.c.a(Unknown Source:0)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at c.a.a.a.g.a(Unknown Source:139)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at c.a.a.a.b.a(Unknown Source:706)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at d.a.c.a.i$a.a(Unknown Source:17)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at android.os.MessageQueue.nativePollOnce(Native Method)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at android.os.MessageQueue.next(MessageQueue.java:336)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:174)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
> 03-08 17:19:08.725 30418 30418 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

onTap function
```
onTap: () {
        if (model.player.playerState.value == PlayerState.stop) {
          model.play(index);
        } else if (model.player.current.value.audio.audio !=
            model.allSongs[index]) {
          model.play(index);
        }
      },
```

play function
```
play(index) {
    player.stop();
    player.open(
        Playlist(
          audios: allSongs,
          startIndex: index ?? 0,
        ),
        loopMode: player.currentLoopMode,
        showNotification: true,
        notificationSettings: NotificationSettings(
            stopEnabled: false,
            seekBarEnabled: false,
            customPlayPauseAction: pause()));

    notifyListeners();
  }
```

**Comment by BilenAhmet** [comment]
@kalismeras61 no, I use android 29

**Comment by dmrcierhn** [comment]
same problem
