### ISSUE TITLE
NoSuchMethodError: No virtual method stopForeground

### ISSUE THREAD

**Issue by medyas** [florent37/Flutter-AssetsAudioPlayer#498]
**Flutter Version**
`Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.17763.1817], locale en-US)`

My version : 
`assets_audio_player: ^2.0.15`

Platform : Android
Device: Nexus 5 (mobile) • android-arm    • Android 6.0.1 (API 23)

**Describe the bug**

When start of the app, i got this crash:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.radioarabica.app, PID: 8462
    java.lang.NoSuchMethodError: No virtual method stopForeground(I)V in class Lcom/github/florent37/assets_audio_player/notification/NotificationService; or its super classes (declaration of 'com.github.florent37.assets_audio_player.notification.NotificationService' appears in /data/app/com.radioarabica.app-1/base.apk:classes5.dex)
        at com.github.florent37.assets_audio_player.notification.NotificationService.displayNotification(NotificationService.kt:307)
        at com.github.florent37.assets_audio_player.notification.NotificationService.access$displayNotification(NotificationService.kt:27)
        at com.github.florent37.assets_audio_player.notification.NotificationService$displayNotification$1.invokeSuspend(NotificationService.kt:141)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

this is caused by: ([source](https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/379eccfde28537a12ed67c614519a546ef590ec1/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt#L300))
```
//fix for https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/139
        if (!action.isPlaying) {
           stopForeground(2)
        }
```

**Comment by zxl777** [comment]
me too.

**Comment by Mayb3Nots** [comment]
@zxl777 Hi can you provide me the device's API andriod level?

**Comment by Mayb3Nots** [comment]
According to the android [docs ](https://developer.android.com/reference/android/app/Service#STOP_FOREGROUND_DETACH)the function `stopForeground()` is only available after API level 24. I think we have to check if the API level before called `stopForeground()`.

**Comment by zxl777** [comment]
@Mayb3Nots 
```
        minSdkVersion 23
        targetSdkVersion 29
```
I changed the minSdkVersion to 24, But app can not worked on the android 6.0 phone.

**Comment by Mayb3Nots** [comment]
> @Mayb3Nots
> 
> ```
>         minSdkVersion 23
>         targetSdkVersion 29
> ```
> 
> I changed the minSdkVersion to 24, But app can not worked on the android 6.0 phone.

Yes that is the whole point. Older version of andriod cant be supported if you wanna use this package. Unless you use my pull request.
