### ISSUE TITLE
Player doesn't work on Flutter Web

### ISSUE THREAD

**Issue by bringbackthedog** [florent37/Flutter-AssetsAudioPlayer#529]
**Flutter Version**
My version : 2.3.0-0.1.pre

**Lib Version**
My version : 3.0.3+2

**Platform (Android / iOS / web) + version**
Platform :  Web

**Describe the bug**
Unable to start the player on Web. Getting the following exception:
```
PlatformException(error, Expected a value of type 'double', but got one of type 'Null', null, null)
Error: PlatformException(error, Expected a value of type 'double', but got one of type 'Null', null, null)
    at Object.createErrorWithStack (http://localhost:43235/dart_sdk.js:5061:12)
    at Object._rethrow (http://localhost:43235/dart_sdk.js:37655:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:43235/dart_sdk.js:37651:13)
    at Object._microtaskLoop (http://localhost:43235/dart_sdk.js:37511:13)
    at _startMicrotaskLoop (http://localhost:43235/dart_sdk.js:37517:13)
    at http://localhost:43235/dart_sdk.js:33288:9

``` 
  

**Small code to reproduce**
```dart
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

main() {
  runApp(MaterialApp(home: MyApp()));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(
        onPressed: () async {
          await AssetsAudioPlayer().open(
            Audio.network(
              "https://www.kozco.com/tech/piano2.wav",
            ),
          );
        },
        child: Text("Play"),
      ),
    );
  }
}
```

**Comment by kalismeras61** [comment]
Use assets_audio_player_web not assets_audio_player

**Comment by dmota** [comment]
Is there any documentation available on how to adapt code written for `assets_audio_player` with `assets_audio_player_web`?

**Comment by franvara** [comment]
I had to add both dependencies and my code worked correctly in web without more code.

  assets_audio_player: ^3.0.3+3
  assets_audio_player_web: ^3.0.3+3

In the dart class I only have the next import:
import 'package:assets_audio_player/assets_audio_player.dart';

I started my project only for android and I adapted to web too.

**Comment by kalismeras61** [comment]
No update closing.
