### ISSUE TITLE
Trying to load music on load but error

### ISSUE THREAD

**Issue by yubarajshrestha** [florent37/Flutter-AssetsAudioPlayer#561]
**Flutter Code**
```dart
class _TestPageState extends State<TestPage> {
  AssetsAudioPlayer player = AssetsAudioPlayer.withId("music");
  Audio audio = Audio(
    "assets/audios/Ukulele.mp3",
  );

  @override
  void initState() {
    openPlayer();
    super.initState();
  }

  Future openPlayer() async {
    await player.open(audio, showNotification: true, autoStart: false);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("AWESOME"),
      ),
      body: Center(
        child: Column(
          children: [
            OutlinedButton(
              onPressed: () async {
                player.play();
              },
              child: Text("Play"),
            ),
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    player.dispose();
    print('dispose');
    super.dispose();
  }
}

```

Everytime I try to play song then I get following error:

```console
W/System.err(16657): com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$NoPlayerFoundException
W/System.err(16657): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:69)
W/System.err(16657): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:87)
W/System.err(16657): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$_findWorkingPlayer$1.invokeSuspend(Unknown Source:12)
W/System.err(16657): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err(16657): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
W/System.err(16657): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(16657): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(16657): 	at android.os.Looper.loop(Looper.java:246)
W/System.err(16657): 	at android.app.ActivityThread.main(ActivityThread.java:8506)
W/System.err(16657): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(16657): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
W/System.err(16657): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/flutter (16657): PlatformException(OPEN, null, null, null)
E/flutter (16657): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(OPEN, null, null, null)
```

And also how can I auto start the song as app loads? It's not working even if I set `autoStart: true`;
Having this issue on null safety version.

**Comment by Shahmirzali-Huseynov** [comment]
@yubarajshrestha  Hello, what did you do for solving? can you help ? i have also this issue

**Comment by yubarajshrestha** [comment]
> @yubarajshrestha  Hello, what did you do for solving? can you help ? i have also this issue

That is the file permission issue. If you play song from url it will play with no issues. But instead of searching various workarounds I moved to just_audio and audio_service.
