### ISSUE TITLE
App keeps stopping 

### ISSUE THREAD

**Issue by sahmirzali** [florent37/Flutter-AssetsAudioPlayer#600]
**Flutter Version**
2.2.3
My version : 2.2.3 

**Lib Version** 3.0.3+6

My version : 3.0.3+6

**Platform (Android / iOS / web) + version**

Platform : Android 11 

**Describe the bug**
 
When I open the audio page app getting crash. and closing. appearing App keeps stopping 

in android 7,8,9,10 there are no problems. only android 11

Real device report :

```
23:42:12 E AndroidRuntime : FATAL EXCEPTION: main
23:42:12 E AndroidRuntime : Process: com.app.arafapp, PID: 694
23:42:12 E AndroidRuntime : java.lang.RuntimeException: Unable to create service com.ryanheise.audioservice.AudioService: java.lang.ClassNotFoundException: Didn't find class "com.ryanheise.audioservice.AudioService" on path: DexPathList[[zip file "/data/app/~~XsMiJNHnec8Kya7_wP4a-A==/com.app.arafapp-1lCmLiozNkV3tV5-EjeO9A==/base.apk"],nativeLibraryDirectories=[/data/app/~~XsMiJNHnec8Kya7_wP4a-A==/com.app.arafapp-1lCmLiozNkV3tV5-EjeO9A==/lib/arm64, /data/app/~~XsMiJNHnec8Kya7_wP4a-A==/com.app.arafapp-1lCmLiozNkV3tV5-EjeO9A==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
23:42:12 E AndroidRuntime : at android.app.ActivityThread.handleCreateService(ActivityThread.java:4204)
23:42:12 E AndroidRuntime : at android.app.ActivityThread.access$1500(ActivityThread.java:237)
23:42:12 E AndroidRuntime : at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
23:42:12  E  AndroidRuntime: at android.os.Handler.dispatchMessage (Handler.java:106)
23:42:12 E AndroidRuntime : at android.os.Looper.loop(Looper.java:223)
23:42:12 E AndroidRuntime : at android.app.ActivityThread.main(ActivityThread.java:7656)
23:42:12 E AndroidRuntime : at java.lang.reflect.Method.invoke(Native Method)
23:42:12 E AndroidRuntime : at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
23:42:12 E AndroidRuntime : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
23:42:12 E AndroidRuntime : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ryanheise.audioservice.AudioService" on path: DexPathList[[zip file "/data/app/~~XsMiJNHnec8Kya7_wP4a-A==/com.app.arafapp-1lCmLiozNkV3tV5-EjeO9A==/base.apk"],nativeLibraryDirectories=[/data/app/~~XsMiJNHnec8Kya7_wP4a-A==/com.app.arafapp-1lCmLiozNkV3tV5-EjeO9A==/lib/arm64, /data/app/~~XsMiJNHnec8Kya7_wP4a-A==/com.app.arafapp-1lCmLiozNkV3tV5-EjeO9A==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
23:42:12 E AndroidRuntime : at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
23:42:12 E AndroidRuntime : at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
23:42:12 E AndroidRuntime : at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
23:42:12 E AndroidRuntime : at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
23:42:12 E AndroidRuntime : at androidx.core.app.CoreComponentFactory.instantiateService(Unknown Source:0)
23:42:12 E AndroidRuntime : at android.app.ActivityThread.handleCreateService(ActivityThread.java:4183)
23:42:12 E AndroidRuntime : ... 8 more
```

**Comment by kalismeras61** [comment]
This is not related to this plugin. Please create issue audio_service package.

**Comment by sahmirzali** [comment]
@kalismeras61 I'm not using audio_service package

**Comment by sahmirzali** [comment]
@kalismeras61 Yasin kardes sadece bu paketi kullaniyorum :/

**Comment by kalismeras61** [comment]
@sahmirzali com.ryanheise.audioservice.AudioService gönderdiğin log'da bu yazıyor. Bu da audio_service paketinin servis ismi.

**Comment by sahmirzali** [comment]
@kalismeras61  teşekkür ederim, bir defa deneme amaçlı kullanmıştım, AndroidManifest.xml dosyasında kalmisti :) simdi duzeldi, tesekkurler
