### ISSUE TITLE
Android error (Audio.network)

### ISSUE THREAD

**Issue by hadukin** [florent37/Flutter-AssetsAudioPlayer#611]
**Flutter Version**

My version : 2.2.3

**Lib Version**

My version : ^3.0.3+3

**Platform (Android / iOS / web) + version**

Platform : Android 

**Describe the bug**

E/ExoPlayerImplInternal( 6714): Playback error
E/ExoPlayerImplInternal( 6714):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 6714):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
E/ExoPlayerImplInternal( 6714):       at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 6714):       at android.os.Looper.loop(Looper.java:154)
E/ExoPlayerImplInternal( 6714):       at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 6714):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
E/ExoPlayerImplInternal( 6714):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:346)
E/ExoPlayerImplInternal( 6714):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 6714):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016)
E/ExoPlayerImplInternal( 6714):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
E/ExoPlayerImplInternal( 6714):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/ExoPlayerImplInternal( 6714):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/ExoPlayerImplInternal( 6714):       at java.lang.Thread.run(Thread.java:761)
E/ExoPlayerImplInternal( 6714):   Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
E/ExoPlayerImplInternal( 6714):       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
E/ExoPlayerImplInternal( 6714):       at com.android.okhttp.Connection.connectTls(Connection.java:235)
E/ExoPlayerImplInternal( 6714):       at com.android.okhttp.Connection.connectSocket(Connection.java:199)
E/ExoPlayerImplInternal( 6714):       at com.android.okhttp.Connection.connect(Connection.java:172)
E/ExoPlayerImplInternal( 6714):       at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
E/ExoPlayerImplInternal( 6714):       at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
E/ExoPlayerImplInternal( 6714):       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
E/ExoPlayerImplInternal( 6714):       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
E/ExoPlayerImplInternal( 6714):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
E/ExoPlayerImplInternal( 6714):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
E/ExoPlayerImplInternal( 6714):       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
E/ExoPlayerImplInternal( 6714):       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
E/ExoPlayerImplInternal( 6714):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:608)
E/ExoPlayerImplInternal( 6714):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:513)
E/ExoPlayerImplInternal( 6714):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:339)
E/ExoPlayerImplInternal( 6714):       ... 6 more
E/ExoPlayerImplInternal( 6714):       Suppressed: javax.net.ssl.SSLHandshakeException: Handshake failed
E/ExoPlayerImplInternal( 6714):           ... 21 more
E/ExoPlayerImplInternal( 6714):           Suppressed: javax.net.ssl.SSLHandshakeException: Handshake failed
E/ExoPlayerImplInternal( 6714):               ... 21 more
E/ExoPlayerImplInternal( 6714):           Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x767ecb335780: Failure in SSL library, usually a protocol error
E/ExoPlayerImplInternal( 6714):   error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (external/boringssl/src/ssl/s3_pkt.c:610 0x767ebf03b6e0:0x00000001)
E/ExoPlayerImplInternal( 6714):   error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (external/boringssl/src/ssl/s3_clnt.c:764 0x767ef083e76a:0x00000000)
E/ExoPlayerImplInternal( 6714):               at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/ExoPlayerImplInternal( 6714):               at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
E/ExoPlayerImplInternal( 6714):               ... 20 more
E/ExoPlayerImplInternal( 6714):       Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x767ecb335780: Failure in SSL library, usually a protocol error
E/ExoPlayerImplInternal( 6714):   error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/s3_pkt.c:610 0x767ebf03b6e0:0x00000001)
E/ExoPlayerImplInternal( 6714):           at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/ExoPlayerImplInternal( 6714):           at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
E/ExoPlayerImplInternal( 6714):           ... 20 more
E/ExoPlayerImplInternal( 6714):   Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x767ecb3
I/ExoPlayerImpl( 6714): Release 62f605d [ExoPlayerLib/2.14.1] [generic_x86_64, Android SDK built for x86_64, unknown, 24] [goog.exo.core]
W/MediaPlayer( 6714): Couldn't open https://store.vas-stream.ru/uploads/mts-rbt/cms/preview/file/29814/bf067379360dc6687c2831bc7f27e41c.mp3?timestamp=1600952291: java.io.FileNotFoundException: No content provider: https://store.vas-stream.ru/uploads/mts-rbt/cms/preview/file/29814/bf067379360dc6687c2831bc7f27e41c.mp3?timestamp=1600952291
E/MediaPlayer( 6714): error (1, -2147483648)

**Small code to reproduce**

```dart
await player.open(
      Audio.network(url),
      autoStart: false,
      playInBackground: PlayInBackground.disabledPause,
);
```

**Comment by CpHeat** [comment]
I'm experiencing the same issue. I can get a remote file to play but no stream unfortunately
