### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by lalLAL95828** [florent37/Flutter-AssetsAudioPlayer#621]
**Flutter Version**

My version : 

**Lib Version**

My version : 

**Platform (Android / iOS / web) + version**

Platform : 

**Describe the bug**

**Small code to reproduce**

```dart
W/.example.douba(17584): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl(17584): Init 7af17b0 [ExoPlayerLib/2.14.1] [generic_x86, Android SDK built for x86, unknown, 30]
I/ExoPlayerImpl(17584): Release 7af17b0 [ExoPlayerLib/2.14.1] [generic_x86, Android SDK built for x86, unknown, 30] [goog.exo.core]
I/TetheringManager(17584): registerTetheringEventCallback:com.example.douban
D/CompatibilityChangeReporter(17584): Compat change id reported: 147600208; UID 10121; state: ENABLED
V/MediaPlayer(17584): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(17584): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/System.err(17584): com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$NoPlayerFoundException
W/System.err(17584): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:70)
W/System.err(17584): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:88)
W/System.err(17584): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$_findWorkingPlayer$1.invokeSuspend(Unknown Source:12)
W/System.err(17584): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err(17584): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
W/System.err(17584): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(17584): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(17584): 	at android.os.Looper.loop(Looper.java:223)
W/System.err(17584): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
W/System.err(17584): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(17584): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/System.err(17584): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/flutter (17584): PlatformException(OPEN, null, null, null)
E/flutter (17584): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(OPEN, null, null, null)
E/flutter (17584): 

```

**Comment by lalLAL95828** [comment]
If the song name is Chinese, this error will be reported

**Comment by kalismeras61** [comment]
Releated to song name. Closing for now.
