### ISSUE TITLE
play asset error on android

### ISSUE THREAD

**Issue by visign3d** [florent37/Flutter-AssetsAudioPlayer#716]
Just trying play some asset sound on android:
```
AssetsAudioPlayer.newPlayer().open(
      Audio("sounds/ui_camera-shutter.wav"),
      autoStart: true,
      showNotification: true,
    );
```

error mesage:
```
I/ViewRootImpl@8c5707f[MainActivity](15905): ViewPostIme pointer 0
I/MSHandlerLifeCycle(15905): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@23b1787[MainActivity]
I/MSHandlerLifeCycle(15905): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@23b1787[MainActivity]
I/MSHandlerLifeCycle(15905): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@23b1787[MainActivity]
I/MSHandlerLifeCycle(15905): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@23b1787[MainActivity]
I/MSHandlerLifeCycle(15905): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@23b1787[MainActivity]
I/MSHandlerLifeCycle(15905): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@23b1787[MainActivity]
I/MSHandlerLifeCycle(15905): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@23b1787[MainActivity]
I/MSHandlerLifeCycle(15905): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@23b1787[MainActivity]
I/MSHandlerLifeCycle(15905): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@23b1787[MainActivity]
I/MSHandlerLifeCycle(15905): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@23b1787[MainActivity]
I/ViewRootImpl@8c5707f[MainActivity](15905): ViewPostIme pointer 1
I/MSHandlerLifeCycle(15905): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@23b1787[MainActivity]
I/ExoPlayerImpl(15905): Init 8b9cb4b [ExoPlayerLib/2.17.1] [p3s, SM-G998B, samsung, 31]
[App] Sound.play : play
I/ExoPlayerImpl(15905): Release 8b9cb4b [ExoPlayerLib/2.17.1] [p3s, SM-G998B, samsung, 31] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource]
V/MediaPlayer-JNI(15905): native_setup
V/MediaPlayerNative(15905): constructor
V/MediaPlayerNative(15905): setListener
V/MediaPlayer(15905): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(15905): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer-JNI(15905): release
V/MediaPlayerNative(15905): setListener
V/MediaPlayerNative(15905): disconnect
V/MediaPlayerNative(15905): destructor
V/MediaPlayerNative(15905): disconnect
W/System.err(15905): com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$NoPlayerFoundException
W/System.err(15905): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:70)
W/System.err(15905): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:88)
W/System.err(15905): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder.access$_findWorkingPlayer(PlayerFinder.kt:26)
W/System.err(15905): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$_findWorkingPlayer$1.invokeSuspend(Unknown Source:15)
W/System.err(15905): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err(15905): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
W/System.err(15905): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(15905): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(15905): 	at android.os.Looper.loopOnce(Looper.java:226)
W/System.err(15905): 	at android.os.Looper.loop(Looper.java:313)
W/System.err(15905): 	at android.app.ActivityThread.main(ActivityThread.java:8669)
W/System.err(15905): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(15905): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
W/System.err(15905): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
I/flutter (15905): PlatformException(OPEN, null, null, null)
E/flutter (15905): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(OPEN, null, null, null)
E/flutter (15905): 

```

flutter version : 3.0.1

**Comment by Sums-shadow** [comment]
same error
how do you solve it?

**Comment by xSuperMu** [comment]
I'm also facing the same error
