### ISSUE TITLE
Playing mp3 file gives NoPlayerFoundException

### ISSUE THREAD

**Issue by PavelTurk** [florent37/Flutter-AssetsAudioPlayer#727]
I am trying to record and play mp3 file. I successfully record it, but can't play it with assets_audio_player. This is my code:

```
static void start(File file) {
    try {
      var _player = AssetsAudioPlayer.newPlayer();
      var path = file.path! + Platform.pathSeparator + file.name!;
      print("path:" + path);
      _player.open(
        Audio(path),
        autoStart: true,
        showNotification: true,
      );
    } catch (e) {
      print(e);
    }
  }
```
And this is output:

```
D/RecordMp3Plugin(19480): record = /data/user/0/temp.myproject.myproject/cache/Record_26_09_2022_14_40_28.mp3
D/RecordMp3(19480): status = START
D/RecordMp3(19480): status = STOP
D/RecordMp3(19480): status = COMPLETE
I/System.out(19480): record complete
I/flutter (19480): path:/data/user/0/temp.myproject.myproject/cache/Record_26_09_2022_14_40_28.mp3
I/ExoPlayerImpl(19480): Init 85b3840 [ExoPlayerLib/2.17.1] [generic_x86_arm, sdk_gphone_x86, Google, 30]
I/ExoPlayerImpl(19480): Release 85b3840 [ExoPlayerLib/2.17.1] [generic_x86_arm, sdk_gphone_x86, Google, 30] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource]
V/MediaPlayer(19480): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(19480): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/System.err(19480): com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$NoPlayerFoundException
W/System.err(19480): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:70)
W/System.err(19480): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:88)
W/System.err(19480): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder.access$_findWorkingPlayer(PlayerFinder.kt:26)
W/System.err(19480): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$_findWorkingPlayer$1.invokeSuspend(Unknown Source:15)
W/System.err(19480): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err(19480): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
W/System.err(19480): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(19480): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(19480): 	at android.os.Looper.loop(Looper.java:223)
W/System.err(19480): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
W/System.err(19480): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(19480): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/System.err(19480): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/flutter (19480): PlatformException(OPEN, null, null, null)
E/flutter (19480): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(OPEN, null, null, null)
E/flutter (19480): 
```
Could anyone say how to fix it?

**Comment by omerrciftcii** [comment]
@PavelTurkish  Did you find any solution for this?

**Comment by RomanSoviak** [comment]
@omerrciftcii didi you find a solution?
