### ISSUE TITLE
ForegroundServiceStartNotAllowedException

### ISSUE THREAD

**Issue by Sanam-Gurung** [florent37/Flutter-AssetsAudioPlayer#801]
Flutter 3.13.1 
Assets audio Player : 3.1.0 

**Platform (Android / iOS / web) + version**

Platform : Android

Fatal Exception: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.goodvibes/com.github.florent37.assets_audio_player.notification.NotificationService
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
       at android.os.Parcel.readParcelable(Parcel.java:3334)
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2421)
       at android.os.Parcel.createException(Parcel.java:2410)
       at android.os.Parcel.readException(Parcel.java:2393)
       at android.os.Parcel.readException(Parcel.java:2335)
       at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7343)
       at android.app.Service.startForeground(Service.java:733)
       at com.github.florent37.assets_audio_player.notification.NotificationService.displayNotification(NotificationService.kt:349)
       at com.github.florent37.assets_audio_player.notification.NotificationService.access$displayNotification(NotificationService.kt:32)
       at com.github.florent37.assets_audio_player.notification.NotificationService$displayNotification$1.invokeSuspend(NotificationService.kt:148)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8309)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

**Comment by seceba** [comment]
I am using 3.1.0. 3.1.1 update and fixed the problem in the other issue?

Other issue: https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/803

**Comment by vbuberen** [comment]
This one is resolved by release `3.1.1`, even though `3.1.1` has another bug mentioned above.

**Comment by imyourdeveloperhere** [comment]
Is this issue resolved? 
I'm using the version "assets_audio_player: ^3.1.1" 

In my android application this issue is occurring, leading to crashes in massive amount of Android 12 & 13 devices.
